MyCRM/urls.py
from django.contrib import admin
from django.contrib.auth import views
from django.urls import path, include

from core.views import index, about
from userprofile.views import signup, myaccount

urlpatterns = [
    path('', index, name='index'),
    path('dashboard/leads/', include('lead.urls')),
    path('dashboard/clients/', include('client.urls')),
    path('dashboard/myaccount/', myaccount, name='myaccount'),
    path('dashboard/teams/', include('team.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('about/', about, name='about'),
    path('signup/', signup, name='signup'),
    path('log-in', views.LoginView.as_view(template_name='userprofile/login.html'), name='login'),
    path('log-out/', views.LogoutView.as_view(), name='logout'),
    path("admin/", admin.site.urls),
    path('admin/', admin.site.urls),
    path('appointments/', include('appointments.urls')),
]

lead/urls.py
from django.urls import path

from . import views 

urlpatterns =[
    path('', views.leads_list, name='leads_list'),
    path('<int:pk>/', views.leads_detail, name='leads_detail'),
    path('<int:pk>/delete/', views.leads_delete, name='leads_delete'),
    path('<int:pk>/edit/', views.leads_edit, name='leads_edit'),
    path('<int:pk>/convert/', views.convert_to_client, name='leads_convert'),
    path('add-lead/', views.add_lead, name='add_lead'),
]

lead/models.py
from django.contrib.auth.models import User
from django.db import models

from team.models import Team

class Lead(models.Model):
    LOW = 'low'
    MEDIUM = 'medium'
    HIGH = 'high'

    CHOICES_PRIORITY = (
        (LOW, 'Low'),
        (MEDIUM, 'Medium'),
        (HIGH, 'High'),
    )

    NEW = 'new'
    CONTACTED = 'contacted'
    WON = 'won'
    LOST = 'lost'

    CHOICES_STATUS = (
        (NEW, 'New'),
        (CONTACTED, 'Contacted'),
        (WON, 'Won'),
        (LOST, 'Lost'),
    )

    team = models.ForeignKey(Team, related_name='leads', on_delete = models.CASCADE)
    name = models.CharField(max_length=225)
    email = models.EmailField()
    description = models.TextField(blank=True, null=True)
    priority = models.CharField(max_length=10, choices=CHOICES_PRIORITY, default=MEDIUM)
    status = models.CharField(max_length=10, choices=CHOICES_STATUS, default=NEW)
    converted_to_client = models.BooleanField(default = False)
    created_by = models.ForeignKey(User, related_name='leads', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
    
    def __str__(self):
        return self.name

lead/forms.py
from django import forms

from .models import Lead

class AddLeadForm(forms.ModelForm):
    class Meta:
        model = Lead
        fields = ('name','email', 'description', 'priority', 'status')

lead/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404

from .forms import AddLeadForm
from .models import Lead
from client.models import Client
from team.models import Team


@login_required
def leads_list(request):
    leads = Lead.objects.filter(created_by = request.user, converted_to_client = False)

    return render(request, 'lead/leads_list.html', {
        'leads' : leads
    })


@login_required
def leads_detail(request, pk):
    lead = get_object_or_404(Lead, created_by=request.user, pk=pk)
    lead = Lead.objects.filter(created_by=request.user).get(pk=pk)

    return render(request, 'lead/leads_detail.html', {
        'lead': lead
    })

@login_required
def leads_delete(request, pk):
    lead = get_object_or_404(Lead, created_by=request.user, pk=pk)
    lead.delete() 

    messages.success(request, 'The lead was successfully deleted')

    return redirect('leads_list')

@login_required
def leads_edit(request, pk):
    
    lead = get_object_or_404(Lead, created_by=request.user, pk=pk)
    if request.method=='POST':
        form = AddLeadForm(request.POST, instance=lead)

        if form.is_valid():
            form.save()

            messages.success(request, 'The changes were saved')
            return redirect('leads_list')
    else:
        form = AddLeadForm(instance=lead)
    
    return render(request, 'lead/leads_edit.html',{
        'form' : form
    })



@login_required
def add_lead(request):

    team = Team.objects.filter(created_by = request.user)[0]

    if request.method == 'POST':
        form = AddLeadForm(request.POST)

        if form.is_valid():
            team = Team.objects.filter(created_by = request.user)[0]

            lead = form.save(commit = False)
            lead.created_by = request.user
            lead.team = team
            lead.save()

            messages.success(request, 'The lead was successfully created')
            return redirect('leads_list')

    else:
        form = AddLeadForm()


    return render(request, 'lead/add_lead.html', {
        'form': form,
        'team' : team
    })

@login_required
def convert_to_client(request, pk):
    lead = get_object_or_404(Lead, created_by=request.user, pk=pk)

    team = Team.objects.filter(created_by = request.user)[0]

    client = Client.objects.create(
        name = lead.name,
        email = lead.email,
        description = lead.description,
        created_by = request.user,
        team = team,
    ) 
    
    lead.converted_to_client = True
    lead.save()

    messages.success(request, 'The lead was converted to the client')

    return redirect('leads_list')

lead/templates/lead/add_lead.html
{% extends 'core/base.html' %}

{% block title %}Add Lead{% endblock %}

{% block content %}
    <div class="py-4 px-6">
        <h1 class="text-xl">Add Lead</h1>

        

        {% if team.plan.max_leads > team.leads.all|length %}
        
            <form method="post" action=".">
                {% csrf_token %}

                {{ form.as_p }}

            <button class="py-3 px-5 bg-teal-600 rounded-xl text-white font-bold transition-colors duration-300 hover:bg-teal-100 hover:text-teal-900">Add Lead</button>
            </form>
        
        {% else %}

        <div class="mt-6 px-6 py-4 bg-red-400 rounded-xl text-white">
            Your team has reached maximum of leads. Your owner must upgrade your plan!
        </div>

        {% endif %}
        
    </div>
{% endblock %}

lead/templates/lead/leads_detail.html
{% extends 'core/base.html' %}

{% block title %}{{ lead.name }}{% endblock %}

{% block content %}
    <div class="py-4 px-6">
        <h1 class="text-xl font-bold">{{ lead.name }}</h1>
        
        {% if lead.description %}
            <p class="font-semibold flex ">Description</p>
            <p class="mb-2">{{ lead.description }}</p>
        {% endif %}

        <p class="font-semibold flex ">Priority</p>
        <p class="mb-2">{{ lead.get_priority_display }}</p>

        <p class="font-semibold flex ">Status</p>
        <p class="mb-2">{{ lead.get_status_display }}</p>

        <p class="font-semibold flex ">Created At</p>
        <p class="mb-2">{{ lead.created_at|date:"D d M Y H:i"}}</p>  

        <p class="font-semibold flex ">Modified At</p>
        <p class="mb-2 flex justify-between">{{ lead.modified_at|date:"D d M Y H:i"}}</p>
        
        <hr class="my-4">

        <a href="{% url 'leads_convert' lead.id %}" class="py-2 px-4 rounded-xl bg-blue-400 text-white">Convert</a>
        <a href="{% url 'leads_edit' lead.id %}" class="py-2 px-4 rounded-xl bg-teal-500 text-white">Edit</a>
        <a href="{% url 'leads_delete' lead.id %}" class="py-2 px-4 rounded-xl bg-red-500 text-white">Delete</a>

        <hr class="my-4">

        <a href="{% url 'leads_list' %}">Back to leads</a>
    
    </div>
{% endblock %}

lead/templates/lead/leads_edit.html
{% extends 'core/base.html' %}

{% block title %}Edit Lead{% endblock %}

{% block content %}
    <div class="py-4 px-6">
        <h1 class="text-xl">Edit Lead</h1>

        <form method="post" action=".">
            {% csrf_token %}

            {{ form.as_p }}

        <button class="py-3 px-5 bg-teal-600 rounded-xl text-white font-bold transition-colors duration-300 hover:bg-teal-100 hover:text-teal-900">Edit Lead</button>
        </form>
    </div>
{% endblock %}

lead/templates/lead/leads_list.html
{% extends 'core/base.html' %}

{% block title %}Leads{% endblock %}

{% block content %}
    <div class="py-4 px-6">
        <h1 class="text-xl font-bold">Leads</h1>
        <a href="{% url 'add_lead' %}" class="block py-4 px-6 bg-teal-600 rounded-xl text-white font-bold transition-colors duration-300 hover:bg-white hover:text-teal-900">Add Lead</a><br>
        
        {% if leads %}
            <div class="mt-6 flex justify-between">
                <p class="py-4 px-2 bg-gray-300 text-gray-900 font-bold w-full rounded-tl-lg">Name</p>
                <p class="py-4 px-2 bg-gray-300 text-gray-900 font-bold w-full">Priority</p>
                <p class="py-4 px-2 bg-gray-300 text-gray-900 font-bold w-full rounded-tr-lg">Status</p>
            </div>

            {% for lead in leads %}
                <div class="flex justify-between">
                    <p class="py-2 px-2 w-full {% cycle 'bg-gray-100 ' '' %}">
                        <a href="{% url 'leads_detail' lead.id %}">{{ lead.name }}</a>
                    </p>
                    <p class="py-2 px-2 w-full {% cycle 'bg-gray-100 ' '' %}">{{ lead.get_priority_display }}</p>
                    <p class="py-2 px-2 w-full {% cycle 'bg-gray-100 ' '' %}">{{ lead.get_status_display }}</p>
                    
                </div>
            
            {% endfor %}

        {% else %}
        <p class="mt-6 px-2">There are no leads in the Data Base yet...</p>
        {% endif %}
    </div>

{% endblock %}